services:
  - type: web
    name: bug-tracker-backend
    env: java
    buildCommand: "cd backend && ./mvnw clean package -DskipTests"
    startCommand: "cd backend && java -jar target/bug-tracking-system-0.0.1-SNAPSHOT.jar"
    plan: free
    autoDeploy: true
envVars:
  - key: SPRING_DATASOURCE_URL
  - key: SPRING_DATASOURCE_USERNAME
  - key: SPRING_DATASOURCE_PASSWORD