services:
  - type: web
    name: bug-tracker-backend
    runtime: docker
    buildCommand: "cd backend && ./mvnw clean package -DskipTests"
    plan: free
    autoDeploy: true
    envVars:
      - fromGroup: bug-tracker
